FROM sibuzu/tensorflow3

# install pytorch
RUN pip3 install --upgrade pip 
RUN pip3 install --upgrade torch torchvision
RUN pip3 install --upgrade graphviz

# Set the locale
RUN locale-gen en_US.UTF-8  
ENV LANG en_US.UTF-8  
ENV LANGUAGE en_US:en  
ENV LC_ALL en_US.UTF-8

EXPOSE 22 3888
WORKDIR "/root"
CMD ["/root/run_sshd.sh"]
