wordpress:
  image: wordpress
  links:
    - wordpressdb:mysql
  environment:
    - WORDPRESS_DB_PASSWORD=jack6819
  ports:
    - 8080:80
  volumes:
    - /dvol/wordpress/code:/code
    - /dvol/wordpress/html:/var/www/html

wp_deeplearn:
  image: wordpress
  links:
    - wp_deeplearndb:mysql
  environment:
    - WORDPRESS_DB_PASSWORD=jack6819
  ports:
    - 8088:80
  volumes:
    - /dvol/wordpress/dlcode:/code
    - /dvol/wordpress/dlhtml:/var/www/html

wordpressdb:
  image: mariadb
  environment:
    - MYSQL_ROOT_PASSWORD=jack6819
    - MYSQL_DATABASE=wordpress
  volumes:
    - /dvol/wordpress/mysql:/var/lib/mysql

wp_deeplearndb:
  image: mariadb
  environment:
    - MYSQL_ROOT_PASSWORD=jack6819
    - MYSQL_DATABASE=wordpress
  volumes:
    - /dvol/wordpress/dlsql:/var/lib/mysql
